"""empty message

Revision ID: a628a8a84841
Revises: 4fd083401781
Create Date: 2021-10-21 17:10:43.536578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a628a8a84841'
down_revision = '4fd083401781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_rating', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_rating', 'comment')
    # ### end Alembic commands ###
