"""empty message

Revision ID: ac584a8877ad
Revises: 72626320d958
Create Date: 2021-10-12 13:38:58.563434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac584a8877ad'
down_revision = '72626320d958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entry', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blog_entry_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('(blog_entry_id IS NOT NULL OR parent_id IS NOT NULL) AND (blog_entry_id IS NULL OR parent_id IS NULL)'),
    sa.ForeignKeyConstraint(['blog_entry_id'], ['blog_entry.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blog_entry_id', 'user_id'),
    sa.UniqueConstraint('parent_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
