"""empty message

Revision ID: 4fd083401781
Revises: 06a1babfc9d8
Create Date: 2021-10-14 02:46:14.177257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fd083401781'
down_revision = '06a1babfc9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.drop_constraint('comment_blog_entry_id_user_id_key', 'comment', type_='unique')
    op.drop_constraint('comment_parent_id_user_id_key', 'comment', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('comment_parent_id_user_id_key', 'comment', ['parent_id', 'user_id'])
    op.create_unique_constraint('comment_blog_entry_id_user_id_key', 'comment', ['blog_entry_id', 'user_id'])
    op.drop_column('comment', 'comment_date')
    # ### end Alembic commands ###
