"""empty message

Revision ID: 06a1babfc9d8
Revises: 3a51d6add53b
Create Date: 2021-10-13 21:32:48.254004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a1babfc9d8'
down_revision = '3a51d6add53b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rating', sa.Column('stars', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rating', 'stars')
    # ### end Alembic commands ###
