"""empty message

Revision ID: 72626320d958
Revises: a35186157078
Create Date: 2021-10-12 13:24:48.499964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72626320d958'
down_revision = 'a35186157078'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_entry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entry', sa.Text(), nullable=False),
    sa.Column('blog_id', sa.BigInteger(), nullable=False),
    sa.Column('published', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_entry')
    # ### end Alembic commands ###
